### ISSUE TITLE
Exclude directories for the dependency section

### ISSUE THREAD

**Issue by akremenetsky** [infraguys/gcl_images#49]
[Main documentation](https://github.com/infraguys/genesis_devtools?tab=readme-ov-file#genesis-configuration-file) 

In build time all directory content is copied to an image but it's not convineint sometimes. We need to add ability to exclude directories for dependencies:
```yaml
  deps:
    - dst: /opt/genesis_core
      path:
        src: ../../genesis_core
      # Exclude some directories
      exclude:
        - .git/
        - .tox/
```

Examples:
- https://github.com/infraguys/gci_base/blob/master/genesis/genesis.yaml
- https://github.com/infraguys/genesis_core/blob/master/genesis/genesis.yaml

DoD:
- Added ability to exclude files/directories during build time for the `path` dependency.
- [Tests extended](https://github.com/infraguys/genesis_devtools/blob/master/genesis_devtools/tests/unit/test_dependency.py)

**Comment by gmelikov** [comment]
@z9xt no problem, feel free to ask questions and show your draft when you're ready.

**Comment by z9xt** [comment]
Is it possible to include pathspec lib in project dependencies?

**Comment by akremenetsky** [comment]
Hi @z9xt,
We would like to specify **files** and **directories** have to excluded. We don't need tricky logic like "delete all nested directory 'foo'" and so on.

### Example 1. Exclude the `build` file from root

Config:
```yaml
  deps:
    - dst: /opt/genesis_core
      path:
        src: ../../genesis_core
      # Exclude some directories
      exclude:
        - build
```

Local files:
```sh
.
├── my_project
│   ├── build
│   └── main.py
├── build
├── project_settings.json
├── requirements.txt
├── setup.cfg
├── setup.py
└── README.md
```

Result in the image after build:
```sh
.
├── my_project
│   ├── build
│   └── main.py
├── project_settings.json
├── requirements.txt
├── setup.cfg
├── setup.py
└── README.md
```

Pay attention the `build` file inside the `my_project` isn't deleted.

### Example 2. Exclude the `build` directory from root

Config:
```yaml
  deps:
    - dst: /opt/genesis_core
      path:
        src: ../../genesis_core
      # Exclude some directories
      exclude:
        - build
```

Local files:
```sh
.
├── my_project
│   ├── build
│   └── main.py
├── build
│   └── main.so
├── project_settings.json
├── requirements.txt
├── setup.cfg
├── setup.py
└── README.md
```

Result in the image after build:
```sh
.
├── my_project
│   ├── build
│   └── main.py
├── project_settings.json
├── requirements.txt
├── setup.cfg
├── setup.py
└── README.md
```

Pay attention the `build` directory inside the `my_project` isn't deleted.

### Example 3. Exclude the `build` directory from `my_project`

Config:
```yaml
  deps:
    - dst: /opt/genesis_core
      path:
        src: ../../genesis_core
      # Exclude some directories
      exclude:
        - my_project/build
```

Local files:
```sh
.
├── my_project
│   ├── build
│   │   └─ main.so
│   └── main.py
├── build
│   └── main.so
├── project_settings.json
├── requirements.txt
├── setup.cfg
├── setup.py
└── README.md
```

Result in the image after build:
```sh
.
├── my_project
│   └── main.py
├── build
│   └── main.so
├── project_settings.json
├── requirements.txt
├── setup.cfg
├── setup.py
└── README.md
```

### Wildcard support

I would say it's optional part. We don't need it at this moment but if you think it's easy to implement let's to that. Most frequently case is `*` in the end of the file/directory names:

```yaml
  deps:
    - dst: /opt/genesis_core
      path:
        src: ../../genesis_core
      # Exclude some directories
      exclude:
        - build_*
```
Don't need to consider other cases.  `Easy` I mean we won't spend more than 1-2 for this feature hours and won't need to extend dependencies. Otherwise let's leave such functionality for the future improvements.

Feel free to ask any other questions.
